//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridBackGround.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class SettingsForm : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsForm defaultInstance = ((SettingsForm)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsForm())));
        
        public static SettingsForm Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DisPackNum {
            get {
                return ((int)(this["DisPackNum"]));
            }
            set {
                this["DisPackNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DisReportNum {
            get {
                return ((int)(this["DisReportNum"]));
            }
            set {
                this["DisReportNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Socket")]
        public string ComMode {
            get {
                return ((string)(this["ComMode"]));
            }
            set {
                this["ComMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TabIndex {
            get {
                return ((int)(this["TabIndex"]));
            }
            set {
                this["TabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string WindowState {
            get {
                return ((string)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6011")]
        public int CMD_Port {
            get {
                return ((int)(this["CMD_Port"]));
            }
            set {
                this["CMD_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int WEB_Port {
            get {
                return ((int)(this["WEB_Port"]));
            }
            set {
                this["WEB_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PicturePath {
            get {
                return ((string)(this["PicturePath"]));
            }
            set {
                this["PicturePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PictureCleanPeriod {
            get {
                return ((int)(this["PictureCleanPeriod"]));
            }
            set {
                this["PictureCleanPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-08-08")]
        public global::System.DateTime PictureCleanTime {
            get {
                return ((global::System.DateTime)(this["PictureCleanTime"]));
            }
            set {
                this["PictureCleanTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PictureCleanAuto {
            get {
                return ((bool)(this["PictureCleanAuto"]));
            }
            set {
                this["PictureCleanAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PictureCleanAtStart {
            get {
                return ((bool)(this["PictureCleanAtStart"]));
            }
            set {
                this["PictureCleanAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PictuerCleanReserveTime {
            get {
                return ((int)(this["PictuerCleanReserveTime"]));
            }
            set {
                this["PictuerCleanReserveTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime PictuerCleanLastTime {
            get {
                return ((global::System.DateTime)(this["PictuerCleanLastTime"]));
            }
            set {
                this["PictuerCleanLastTime"] = value;
            }
        }
    }
}
